### ISSUE TITLE
Flexgrid replacement

### ISSUE THREAD

**Issue by SomeAreDead** [Kr00l/VBFLXGRD#1]
Hi, as a replacement for flexgrid in VB6 does this control all unicode characters? i.e. does it do the job that the third party control like UniFlexgrid does? We're looking to replace that control as it simply won't run in a 64bit environment

**Comment by dexwerx** [comment]
It was definitely written to support Unicode ie all unicode characters. 
Please try it out, and post any bugs.
Unicode was one of the driving motivations for Krools controls :)
