### ISSUE TITLE
Event CompareText - Text arguments should be As String instead of As Long

### ISSUE THREAD

**Issue by Kr00l** [Kr00l/VBFLXGRD#10]
There is an issue in the CompareText event that the Text1 and Text2 arguments should have been `As String` instead of `As Long`

**Comment by NBechtloff** [comment]
Sure. Should Text1 and Text2 be ByRef or ByVal?

**Comment by Kr00l** [comment]
@NBechtloff ByVal. It should not be allowed to change the text while sorting. Thanks!
I give you access again here.

**Comment by Kr00l** [comment]
@NBechtloff works great, done. Thousand thanks!
