### ISSUE TITLE
Scroll Bar Events

### ISSUE THREAD

**Issue by dannyblankenbyl** [Kr00l/VBFLXGRD#11]
HI I've had this issue with MSFLEXGRID and I see the same situation with VBFLEXGRID.
I'm running a fore ground / back ground situation in VB6

Do
Doevents
main loop here
Loop

All goes swell until I click and hold down the scroll bar button at which point the loop stops dead till the scroll button is released.
I think its caused by lots of events coming from the scroll button.
Is there a way I can reduce the number of events? 
It even happens when I'm not moving the button.
Thanks
Danny

**Comment by Kr00l** [comment]
That's normal and I can't do anything about this. The scrollbar will enter also a modal message loop when you press a left mouse button click. Your Doevents will give control to that modal message loop and will return to "your loop" when it's finished.
