### ISSUE TITLE
Office 2016 Support

### ISSUE THREAD

**Issue by LongBit** [Kr00l/VBFLXGRD#5]
Im trying to use the VBFLXGRD in an VBA application in Excel. Registrering the ocx and using it in Office 2013 works great. But when i´m trying to use it in Office 2016 im getting an error, that ther are no "self registering components inside the file".

What should i do?

**Comment by LongBit** [comment]
Is it possible, that VBFLXGRD is not working in x64 environments of Office? My 2013 Office is running in 32 bit while the Office 2016 Installation is the 64bit Version of office.

**Comment by Kr00l** [comment]
Yes, VBFLXGRD is done by VB6 (32 bit)
Therefore only a 32 bit client can host VBFLXGRD.
Even MS recommends to install Office in 32 bit, because of the ActiveX problem.
