### ISSUE TITLE
Is there any option to provide .NET interop

### ISSUE THREAD

**Issue by sdon2** [Kr00l/VBFLXGRD#9]
Hi,

I've tried to create interop assemblies using *aximp.exe* to use it (ActiveX version) in my VB.NET project.

But, I've got an error stated
```
AxImp Error: Error loading type library/DLL. (Exception from HRESULT: 0x80029C4A (TYPE_E_CANTLOADLIBRARY))
```

#Note: I am able to register the ocx

Is there any way to make it interoperable with VB.NET runtime?

Thanks,
Saravanakumar Arumugam

**Comment by Kr00l** [comment]
Try this forked version:
https://github.com/rjdunnill/VBFLXGRD.NET
